package schema

import (
	"time"

	"github.com/shopspring/decimal"
)

const (
	PaymentGatewayStatusSuccessful = "SUCCESSFUL"
	PaymentGatewayStatusFailed     = "FAILED"
)

type CreatePayment struct {
	OrderID    int64           `json:"order_id"`
	CustomerID int64           `json:"customer_id"`
	Currency   string          `json:"currency"`
	Amount     decimal.Decimal `json:"amount"`
}

type CreateGatewayPayment struct {
	PaymentID  string          `json:"payment_id"`
	OrderID    string          `json:"order_id"`
	Amount     decimal.Decimal `json:"amount"`
	Currency   string          `json:"currency"`
	WebhookURL string          `json:"webhook_url"` // Target URL to send the payment result callback
}

// GatewayResponse represents the payload received FROM the external payment gateway API.
type GatewayResponse struct {
	// TransactionID is the unique identifier generated by the payment gateway's engine.
	TransactionID string `json:"transaction_id"`

	// RedirectURL is the secure checkout page link where the frontend must redirect the user
	// to complete the payment (e.g., for 3D Secure OTP verification or bank page).
	RedirectURL string `json:"redirect_url"`

	// IsRejected indicates if the gateway immediately blocked the transaction during the synchronous request
	// (e.g., because the card number format is invalid, or the merchant account is restricted).
	IsRejected bool `json:"is_rejected"`

	// IsInstantSuccess indicates if the transaction was approved immediately without asynchronous redirects
	// (rare for web checkouts, but possible for specific API tokens or recurring payments).
	IsInstantSuccess bool `json:"is_instant_success"`

	// ErrorMessage holds the human-readable reason for failure if IsRejected is true.
	ErrorMessage string `json:"error_message,omitempty"`
}

type PaymentResult struct {
	PaymentID   int64  `json:"payment_id"`
	OrderID     int64  `json:"order_id"`
	CustomerID  int64  `json:"customer_id"`
	Status      string `json:"status"`
	RedirectURL string `json:"redirect_url"`
}

type WebhookParams struct {
	PaymentID string `json:"payment_id"`
	OrderID   string `json:"order_id"`
	Status    string `json:"status"`
}

type PaymentStatusInfo struct {
	CustomerID int64 `json:"customer_id"`
	OrderID    string
	Status     string
	UpdatedAt  time.Time
}
